aruco_node:
  ros__parameters:
    # Ajustar esto al frame de la cámara en el URDF de tu rover.
    camera_frame: camera_link 
    # El tamaño del lado de los marcadores ArUco en metros. DEBES AJUSTAR ESTO A TUS MARCADORES REALES.
    marker_size: 0.2 # Ejemplo: 5 cm
    # El ID del diccionario ArUco a utilizar. DICT_4X4_50 es común.
    aruco_dictionary_id: DICT_4X4_50 
    # El tópico de la imagen de la cámara en tu rover.
    image_topic: /camera/image_raw 
    # El tópico de la información de la cámara en tu rover.
    camera_info_topic: /camera/camera_info 
    output_frame: base_footprint