aruco_node:
  ros__parameters:
    # El frame de la cámara en Gazebo. Para TurtleBot3 con cámara de profundidad, suele ser 'camera_rgb_optical_frame'.
    camera_frame: camera_rgb_optical_frame 
    # El tamaño del lado de los marcadores ArUco en metros. DEBES AJUSTAR ESTO A TUS MARCADORES REALES.
    marker_size: 0.2 # Ejemplo: 5 cm
    # El ID del diccionario ArUco a utilizar. DICT_4X4_50 es común.
    aruco_dictionary_id: DICT_4X4_50 
    # El tópico de la imagen de la cámara. Para TurtleBot3 simulado, suele ser '/camera/image_raw'.
    image_topic: /camera/image_raw 
    # El tópico de la información de la cámara. Para TurtleBot3 simulado, suele ser '/camera/camera_info'.
    camera_info_topic: /camera/camera_info 
    # El frame de referencia en el que se publicarán las poses de los marcadores. 'base_link' es una buena opción.
    output_frame: base_link