ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    # Frames vitales para RViz
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # Configuración de Odometría (Ruedas del C++)
    odom0: odom_gazebo
    odom0_config: [false, false, false, # X, Y, Z (Posición) -> FALSE
                   false, false, false, # Roll, Pitch, Yaw -> FALSE
                   true,  true,  false, # VX, VY, VZ (Velocidad lineal) -> TRUE
                   false, false, true,  # Vroll, Vpitch, Vyaw -> TRUE
                   false, false, false]
    odom0_queue_size: 10

    # Configuración de IMU (Gazebo)
    imu0: imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_queue_size: 10